game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/MeleeCombatStrategy.kt
Corrected distance required for melee combat to start.
=> fix: correct melee attack range distance to account for running

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/Skills.kt
=> Change MAX_COMBAT_LVL to include summoning

game/plugins/src/test/kotlin/gg/rsmod/plugins/api/ext/ContainerExtTests.kt
(note: skipped as part of prev. branch merge)
=> fix: issue with ItemContainer

build.gradle, game/build.gradle, game/plugins/build.gradle, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/MeleeCombatStrategy.kt, gradle/properties.gradle, net/build.gradle, net/src/main/kotlin/gg/rsmod/net/codec/login/LoginDecoder.kt
- Update Kotlin to the latest stable version
- Small changes to ensure it still compiles
- Use `implementation` instead of `compile` in the build.gradles
=> Update kotlin to 1.8.0

build.gradle, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/shops/ItemCurrency.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/trading/impl/TradeSession.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/trading/trading.plugin.kts, game/src/main/kotlin/gg/rsmod/game/sync/segment/PlayerUpdateBlockSegment.kt, util/src/main/kotlin/gg/rsmod/util/Misc.kt, util/src/main/kotlin/gg/rsmod/util/io/Xtea.kt
Removes all compile time warnings from the `util` module
=> remove compile warnings from util module

net/src/main/kotlin/gg/rsmod/net/codec/login/LoginDecoder.kt, net/src/main/kotlin/gg/rsmod/net/packet/GamePacketBuilder.kt
Removes all compile time warnings from the `net` module
=> remove compile warnings from net module

game/src/main/kotlin/gg/rsmod/game/Server.kt, game/src/main/kotlin/gg/rsmod/game/fs/def/AnimDef.kt, game/src/main/kotlin/gg/rsmod/game/fs/def/NpcDef.kt, game/src/main/kotlin/gg/rsmod/game/fs/def/ObjectDef.kt, game/src/main/kotlin/gg/rsmod/game/model/World.kt, game/src/main/kotlin/gg/rsmod/game/model/combat/DamageMap.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/model/region/Chunk.kt, game/src/main/kotlin/gg/rsmod/game/model/skill/SkillSet.kt, game/src/main/kotlin/gg/rsmod/game/model/weight/WeightNodeSet.kt, game/src/main/kotlin/gg/rsmod/game/plugin/KotlinPlugin.kt, game/src/main/kotlin/gg/rsmod/game/service/serializer/PlayerSerializerService.kt, game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSerializer.kt
Fixes all compile time warnings in the `game` module
=> Remove compile warnings from game module

build.gradle, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/ContainerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/ItemExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/PawnExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/formula/MeleeCombatFormula.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/formula/RangedCombatFormula.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/MeleeCombatStrategy.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/RangedCombatStrategy.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Foods.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/Potions.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/MagicSpells.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/sheep/sheep_shear.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fishing/FishingTool.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/woodcutting/Woodcutting.kt
Fix compile-time warnings in `plugins` module
=> Remove compile warnings from plugins module

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/DropTableType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/PickpocketTarget.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/Pickpocketing.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/stalls/StallTarget.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/stalls/Stalls.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/thieving.plugin.kts
- Implements stall thieving
- Data for all stalls except for wine stall
- Failing to steal from a stall (because a nearby npc spotted you) is not yet implemented. This requires more work (or a function I haven't yet found) to be able to gather all nearby npcs
=> Thieving stalls

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/smithing/SmeltingAction.kt, game/src/main/kotlin/gg/rsmod/game/model/World.kt
According to the [osrs wiki](https://oldschool.runescape.wiki/w/Iron_ore), smelting iron bars has a 50% chance of failure, regardless of level.
=> fix: iron ore has 50-80 percent chance to smelt

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/firemaking/FiremakingAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/firemaking/firemaking.plugin.kts
Tries to fix the path finding when firemaking. It's still not perfect, but already a significant improvement. Completely fixing this is somewhat harder, so I'll create an issue for that instead.
Also ensures logs can be lit directly on the ground.
=> Fix firemaking walk

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/Mining.kt
Reverts the earlier revert, with the fix to the bug
=> fix: cannot 0-tick ores

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/crate_of_hammers.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/take_hatchet.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/chicken/chicken.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/cow/cow.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_cabbage.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_flax.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_onion.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_potato.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_wheat.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/cooking/CookingAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/Mining.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/PickaxeType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/RockType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/mining.plugin.kts
Updated take-hatchet plugin.
Added chicken force-chat plugin.
Added cow force-chat plugin.
Added pickup sound to picking plugins.
Fixed cooking action not stopping when cooking over a fire that turns into ashes.
Edited mining plugin:
- Added support for all gilded pickaxes with proper animations.
- Added sound for when you successfully mine ore.
- Added the sound and message for when trying to mine an already depleted ore.
=> Plugin edits.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/woodcutting/Woodcutting.kt
Fixes npc directions to actually face the direction they are set to
=> fix: Proper npc direction

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/bobs_axes.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/crate_of_hammers.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/donie.plugin.kts
- Update Bob's dialogue
- Update Donie's dialogue
- Removed a tiny easter egg I forgot I added to the crate of hammers in the Lumbridge furnace workshop
=> fix: dialogue updates

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/alkharid/dommiks_crafting_store.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/alkharid/spawns_13105.plugin.kts
Add ground item spawns to region 13105
Add Dommik's Crafting Store dialogue and shop
=> More Al-Kharid Content

game/src/main/kotlin/gg/rsmod/game/model/entity/GameObject.kt
fix: Object transform state checking v4
=> Object transform state checking v4

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/beefy_bill.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/spawns_12595.plugin.kts
I gave Beefy Bill a preliminary support plugin.
- add logic to bank items.
- add a few more dialogue options.
=> WIP content: added preliminary Beefy Bill NPC

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/stalls/StallTarget.kt
Adds the wine stall, and fixes some incorrect empty stall ids
=> fix: add wine stall, fix empty stall ids

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/gems/GemAction.kt
This fixes non-fragile gems turning to crushed gems when cut.
=> Gem cutting fix

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/draynor/mizgog.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/quests/impl/ImpCatcher.kt, game/src/main/kotlin/gg/rsmod/game/model/quest/Quest.kt
=> feat: imp catcher quest

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/draynor/mizgog.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/quests/impl/ImpCatcher.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/stalls/StallTarget.kt
- Small textual fixes to the quest overview
- Implements the trade option on Mizgog
- Now really use the correct empty wine stall id
=> Imp catcher fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/leather/LeatherAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/leather/LeatherData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/leather/LeatherItem.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/leather/leather_crafting.plugin.kts, util/src/main/kotlin/gg/rsmod/util/Misc.kt
- Leather crafting is now possible.
Includes: Leather, Hard Leather, Snakeskin, Yak Hide & all Dragonhides.
- Added a formatting function to automatically add "a", "an" or "some" in front of a string depending on appropriate cases.
=> feat: Leather Crafting

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/GameframeTab.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/beefy_bill.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/spawns_12595.plugin.kts
- changed spawn direction for bill
- added dialogue and logic checks
- added bank transport function
- fixed tinderbox item id in store
- set minimum for bill to transport to 10 of respective item
- none
=> feat: finished beefy bill plugin

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/GameframeTab.kt
- changed the values to their correct options
- none
=> feat: updated GameframeTab

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/melee_instructor.plugin.kts
- refined melee instructor dialogue (used void server as reference)
- skillcape prompt handling
- tab switching during dialogue
- training sword & shield logic checks
- check for previously earned skillcapes and award trimmed version accordingly
=> content: melee combat instructor

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/ranged_instructor.plugin.kts
- added ranged instructor using dialogue from void
- added a 30m timer for claiming items from tutors
- add "from Tutorial Island" when content is added. String has been commented out.
=> content: ranged tutor

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/magic_instructor.plugin.kts
- added magic tutor dialogue from void
- use tutor claim timer (30m)
- check if rune mysteries is completed, show dialogue accordingly
- ???
=> content: add magic tutor

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Items.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/global/Seeds.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/duck_level_1.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/farmer_level_7.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/ham_guard_level_12_18_22.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/spider_level_1.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/unicorn_level_15.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/PickpocketTarget.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/starter/starter_kit.plugin.kts
Adds npc definitions for
- level 1 spider
- unicorn
- ham guard
- duck/drake
- farmer
Also sets the default value for deposit-x and withdraw-x to 50 for new accounts
=> feat: npc definitions for lumbridge

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/guard_level_21.plugin.kts
Adds Varrock guard definitions
=> feat: varrock guards

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/dark_wizard_lvl_20.plugin.kts
Adds the dark wizards south of varrock
=> feat: varrock dark wizards

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/king_scorpion_level_32.plugin.kts
=> feat: king scorpion

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/market_guard_level_20.plugin.kts
Adds the draynor market guard combat definition
=> feat: draynor market guard combat def

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/stalls/StallTarget.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/stalls/Stalls.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/thieving.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt
Ensures guards will attack any nearby players that attempt to steal from a stall. For now only Draynor is implemented, since other stall hubs have no spawns yet
=> feat: guards will stop people from stealing from stalls

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/bank/Bank.kt
Check the amount of the item properly
=> fix: deposit more than one unstackable item at a time

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts
=> ::Give command, ::Restore command

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/gems/gem_crafting.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/glassblowing/glassblowing.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/leather/LeatherAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/leather/leather_crafting.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/other/combination_crafting.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/spinning/spinning_wheel.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/tanning/tanning.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/weaponry/battlestaff_crafting.plugin.kts
- fixed player being able to run then craft
=> fix: player will now stop moving upon doing any crafting action

data/cfg/music/music_by_region.yaml, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/music/RegionMusicService.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/music/region_songs.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/sync/task/PlayerPostSynchronizationTask.kt
- Fixed an issue with "on_enter_region" & "on_exit_region" plugins not executing when they should.
- Fixed the regional music plugin.
=> Regional Music

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/stringing/BowItem.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/stringing/BowStringAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/stringing/StringData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/stringing/stringing.plugin.kts
- added bow stringing (no crossbows yet)
=> feat: stringing bows

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/cooking/CookingAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/gems/GemAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/glassblowing/GlassblowingAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/leather/LeatherAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/spinning/SpinningAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/weaponry/BattlestaffAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/weaving/WeavingAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/whittling/WhittleAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/smithing/SmithingAction.kt
=> fix: remove a bunch of return@repeat to prevent spamming of actions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/PickpocketTarget.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/Pickpocketing.kt
- Adds the appropriate message when thieving from a dead or dying npc
- Small fix to the way gloves of silence work
=> fix: cannot thieve from dead npc

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/other/polished_button.plugin.kts
=> feat: polished buttons

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Items.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/equipment/equipment.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/citizen_level_2.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/goblin_level_2.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/goblin_level_5.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/guard_level_21.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/HerbData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/PotionData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/prayer/burying/bone_burying.plugin.kts
Added ability to open up equipment bonus interface
Added ability to open kept on death interface
-
=> Open equipment bonus interface & open kept on death interface

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/Potion.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/Potions.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/potionDrinking.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/arrows/ArrowAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/HerbData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/clean_herb.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/mixing/CreateFinishedPotionAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/mixing/CreateUnfinishedPotionAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/mixing/PotionData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/mixing/mix_potion.plugin.kts, game/src/main/kotlin/gg/rsmod/game/message/handler/ClickMapHandler.kt
- Herb cleaning.
- Potion making.
=> Herblore Progress

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/white_knight_level_36.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/white_knight_level_38.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/white_knight_level_39.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/white_knight_level_42.plugin.kts
Adds definitions for white knights
=> feat: white knights

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12598.plugin.kts
=> added grand exchange spawns

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/Skills.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/skillguides/skill_guides.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/cow/cow.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/experience_up.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/level_up.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/plugin/KotlinPlugin.kt, game/src/main/kotlin/gg/rsmod/game/plugin/PluginRepository.kt, game/src/main/kotlin/gg/rsmod/game/service/game/ItemMetadataService.kt
Added correct level up messages in gamechat when reaching certain milestones 
Added message reaching target of xp & level in chatbox & resets ur current target 
Added a check in cow plugin to now say Moo if dead. 
Added a new plugin for gaining experience, similair to level_up.plugin
=> Levelup Messages, Experience gained Plugin, Cow fix

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/aggro/npc_aggro.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/black_demon_lvl_172.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/chaos_druid_lvl_13.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/dark_wizard_lvl_20.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/dark_wizard_lvl_7.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/giant_spider_level_2.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/hill_giant_lvl_28.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/hobgoblin_armed_lvl_28.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/jail_guard_level_26.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/king_scorpion_level_32.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/lesser_demon_lvl_82.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/scorpion_level_14.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/skeleton_lvl_21.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/skeleton_lvl_22.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/skeleton_lvl_25.plugin.kts
- Added aggro DSL to monster definitions that require it
- Improved aggression handler, mainly focused on the timer
=> Aggro improvements

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt
- Added level-up dialogue message change from PR #135
=> chore: update level-up dialogue message

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt
=> chore: force merge #135

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/other/CombinationAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/other/CombinationData.kt
ex: Amulet messages when putting balls of wool on them.
=> feat: Add the ability to put custom messages to CombinationActions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/deadly_red_spider_level_34.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/skeleton_level_45.plugin.kts
- Adds the level 45 skeleton
- Fixes the drop table of the level 25 skeleton. That skeleton is armed, so should use another drop table
- Adds the deadly red spider
=> feat: some more combat definitions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/clean_herb.plugin.kts
- Adds a level check when cleaning herbs
- Corrects the player message when cleaning a herb
=> fix: check for level when cleaning herbs

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/dwarven_mines/mining_guild_door.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/wilderness_wall.plugin.kts
- Re-installed the wilderness wall plugin
- Added @raynna's mining guild doorway entrance from dwarven mines plugin
=> Wilderness wall/Mining Guild doorway entrance

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/dwarven_mines/dwarf_mining_guild_entrance.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/dwarven_mines/mining_guild_door.plugin.kts
=> Update dwarven mine stuff

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/SpellbookData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/jewelleryenchanting/EnchantmentData.kt
=> Enchantment spells

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/furnaces/furnaces.plugin.kts
Adjusted furnace priorities from comment on PR #160
=> chore: Adjusted priority as mentioned

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/cookingrange/seawead_cooking.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/furnaces/furnaces.plugin.kts
- Added the possibility of making soda ash by burning seaweed on a cooking range/stove
- Added the possibility of making molten glass by using a bucket of sand and/or soda glass on a furnace.
Not at all, code is pretty self explainatory I believe. Can be modified for documentation if necessary.
=> feat: Molten glass making process

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/jewellery/JewelleryAction.kt
=> fix: jewellery crafting locking but not unlocking

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/skilling/jewellery_crafting_interface.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/skilling/silver_crafting_interface.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/jewellery/JewelleryAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/silver/SilverAction.kt
=> chore: fixes silver/jewellery crafting queues

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/RockType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/smithing/smithing.plugin.kts
Adds a missing rock and a missing anvil
=> fix: add a missing rock in al kharid mine and anvil in falador

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_2hsword_lvl_10.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_greataxe_lvl_10.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_lvl_8.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/black_knight_level_33.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/goblin_level_5.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/ram_level_2.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/thief_level_16.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/thug_level_10.plugin.kts
Adds definitions for
- Black knight
- Thug
- Thief
- lvl-8 barbarian
Also adds some new ids to existing definitions
=> feat: combat definitions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_2hsword_lvl_10.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_greataxe_lvl_10.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_greataxe_lvl_17.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_lvl_9.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_spear_lvl_10.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_twohand_sword_lvl_10.plugin.kts
- Fix barbarian npc definitions conflicts.
=> fix: Fix barbarian definitions conflicts.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/watersource/WaterContainerData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/watersource/fill_water.plugin.kts
- Added a way of filling water recipients with water at water sources.
- Added the "empty" option on said water recipents.
Yes.
=> feat: Filling & emptying water recipients.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/taverley/kaqemeex.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/taverley/sanfew.plugin.kts
- removed the variable "druidicRitual", can just use regular DruidicRitual instead. 
- ^^ possibly caused crashes??
not applicable
=> fix: potential crashing fix

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_lvl_8.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/cave_goblin_level_3.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/ghost_level_19.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/giant_rat_level_6.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/hobgoblin_armed_lvl_28.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/hobgoblin_level_28.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/hobgoblin_unarmed_level_28.plugin.kts
- hobgoblins
- lvl 8 barbarian
- cave goblins
- extra ghost
- lvl 6 giant rat
And yes: this time there are no duplicate ids :)
=> feat: more combat definitions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/dwarf_level_10_11.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/zombie_lvl_24.plugin.kts
=> feat: more combat defs

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/jewelleryenchanting/EnchantmentData.kt
=> fix: amulet enchanting

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/RockType.kt
=> fix: silver rocks at s-w varrock mine

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/stalls/Stalls.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt
=> fix: check if pawns are alive/not invisible before attacking

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/cassies_shield_shop.plugin.kts
=> fix: cassies shield shop stock

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/taverley/kaqemeex.plugin.kts
=> fix: druidic ritual initializer 

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/level_up.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt
=> fix: level up priority queue, and unlock on interrupt queues

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/runecrafting/Tiara.kt
=> fix: tiara altar unlocks

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/watersource/WaterContainerData.kt
=> fix: proper vial item id for water sources

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/bankers/bankers.plugin.kts
- Added Functionality for Varrock East Female Bankers, Falador Bankers, and Grand Exchange Bankers.
- Added Banker Dialogue and expressions
- 
Yes, cross referenced with Runescape 3 data 3-15-2023, and Runescape Wiki dating back to 2016.
=> Bankers Dialogue & Expressions Update

data/cfg/objs.yml, game/src/main/kotlin/gg/rsmod/game/model/MovementQueue.kt
- Fixes issue: https://discord.com/channels/1055304546521469019/1085540252959121418
=> fix: issue with movement on type change

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/dblexperience/bonus_experience.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/dblexperience/double_experience.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/runetek5.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/experience_up.plugin.kts, game/src/main/kotlin/gg/rsmod/game/GameContext.kt, game/src/main/kotlin/gg/rsmod/game/Server.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/model/timer/Timers.kt
- Adds varps, timers for Bonus Experience
- Adds calculator for bonus experience based on elapsed time
- Adds game.yml configuration for if bonus experience is live or not
- Ensures proper experience is granted based on multiplier
- Yes
=> Bonus Experience

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/taverley/jatix.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/packs/PackData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/packs/packs.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/PestleAndMortarData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/pestleAndMortar.plugin.kts
- Adds packs to the herblore shop and decreases the stock of some items to be in line with 2011
- Allows opening of packs
- Adds most non-quest pestle and mortar interactions
No, the code is too simple and small
=> feat: update herblore shop stock, add pestle and mortar interactions, add packs

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/level_up.plugin.kts
=> feat: no longer interrupt queues on levelup

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/smithing/data/BarProducts.kt, game/src/main/kotlin/gg/rsmod/game/fs/def/NpcDef.kt, game/src/main/kotlin/gg/rsmod/game/sync/segment/PlayerUpdateBlockSegment.kt
=> Fix updating block

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/dwarven_mines/mining_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/ring_of_dueling.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/TeleportType.kt
- Added the ring of duelling
- Supports equipment menu options, or by "rubbing" the ring
- Added proper dialogue based on this video: https://youtu.be/4B3yXJvPBPg?t=149
- Yes, for the majority of it
=> Ring of duelling

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/level_up.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt
=> fix: issue with level up queues, resting breaking

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/WeaponStyleOption.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatConfigs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/MagicCombatStrategy.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/MeleeCombatStrategy.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/RangedCombatStrategy.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt
Bunch of Combat related fixes for weapontype, styles, experience etc
As much as i could
=> Bunch of Combat related fixes for weapontype, styles, experience etc

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Food.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/GrindAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/PestleAndMortarData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/pestleAndMortar.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/bankers/bankers.plugin.kts
- Added itembox/loop actions for Pestle and Mortar
- Yes
=> Pestle mortar loop actions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/GrindAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/PestleAndMortarData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/pestleAndMortar.plugin.kts
=> chore: update p&m classes

game/src/main/kotlin/gg/rsmod/game/Server.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/model/varp/VarpSet.kt
=> fix: issue with bxp calculation

game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
=> fix: issue with "Bonus:" varp

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/dairy_cow.plugin.kts
- Added the ability to milk regular dairy cows
- Yes
=> feat: ability to milk dairy cows

game/src/main/kotlin/gg/rsmod/game/plugin/PluginRepository.kt
=> chore: prev commit

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/slayer.plugin.kts
=> fix: force check assignments

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/dwarf_level_10_11.plugin.kts
=> fix: dwarf slayer assignment

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/data/SlayerMaster.kt
=> fix: remove minotaur from assignment list

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/burthorpe/rogues_den.plugin.kts
=> feat: add emerald banker in rogues den

game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt
=> fix: issue with overlap with range/magic

game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
=> chore: temp disable locking logout

data/packets.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/following/following.plugin.kts, game/src/main/kotlin/gg/rsmod/game/message/MessageDecoderSet.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/MapBuildCompleteHandler.kt, game/src/main/kotlin/gg/rsmod/game/sync/segment/PlayerLocationHashSegment.kt, game/src/main/kotlin/gg/rsmod/game/sync/segment/PlayerTeleportSegment.kt, game/src/main/kotlin/gg/rsmod/game/sync/segment/PlayerUpdateBlockSegment.kt
- Fixed an issue with players desyncing height levels, meaning you'll no longer have invisible or be invisible to others.
- Fixed an issue with NPC aggression not resetting properly (still need to implement 21x21 chunks for this, for now it's based on region)
- Added more fail-safes to updating entities on region changes (MapBuildComplete packet now sends entity updates)
- Fixed an issue with directions not being sent properly on region changes
- No, as these are fixes
=> Region issues

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/agility/gnome_agility.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/Appearance.kt, game/src/main/kotlin/gg/rsmod/game/model/Direction.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/sync/segment/PlayerUpdateBlockSegment.kt
Added Agility Gnome Course (first level)
Added ability to change renderanimation
=> Agility & Render Animations

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/runecrafting/Altar.kt
Altar updated by rcy
Update Altar.kt
=> Altar update by rcy

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/games_necklace.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/ring_of_kinship.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/equipment/equipment.plugin.kts
- Added games necklace
- Moved ring of kinship to jewellery
- Fixed an issue with equipment options opcodes
- Yes
=> feat: games necklace

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatConfigs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/RangedCombatStrategy.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/ranged/RangedProjectile.kt
Fixed a bug where it wouldn't remove arrows when ranging from certain arrows. 
Fixed chinchompa attack animation
Added training arrows projectile
=> Range bugfixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/gameframe/world_map.plugin.kts
=> feat: animation for map reading

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/beefy_bill.plugin.kts
as item_on_npc was fixed, could do everything properly for bill :D
=> update beefy bill plugin

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt
Made calculations for combat level correct to match runescapes
=> change in calculateAndSetCombatLevel()

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/charter.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/farmingInteractions.plugin.kts
=> fix: charter boat interface destination

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Objs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/core/WorldFarmingManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/CompostBin.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/CompostBinState.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/farmingInteractions.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/FarmingManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/PatchVarbitUpdater.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/VarbitUpdater.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/CompostBinHandler.kt
Adds functionality to compost bins
Yes
=> feat: compost bins

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/agility/gnome_agility.plugin.kts
=> fix: full lock agility

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Objs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Patch.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/PlantingTool.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Seed.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/SeedType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/blocks/Growth.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/npcs/Farmer.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/PlantingHandler.kt
Adds hops patches
No, mostly just data
=> feat: Hops

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/crumbling_wall.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/wilderness_wall.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/agility/gnome_agility.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/ForcedMovement.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
Redone gnome agility & forcemovement method to avoid people getting stuck while doing agility.
=> Agility fix

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/CharterType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/charter.plugin.kts
Fixed issue where it wouldnt remove fading interface at end of a charter.
Fixed up timing of fading & unfading and added a weak queue for sending an dialoguebox message but still be able to walk away from the dialoguebox
=> Charter ship interface fix

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/cooking/CookingAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/cooking/raw_food_cooking.plugin.kts
Fixed cooking ticks & also added so its instant without dialogue if u have one only of the used item.
=> Cooking fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/varrock_sewers.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/combat.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/formula/RangedCombatFormula.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/bank/Bank.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Food.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/resting/Resting.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/RockType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/util/anticheat/anti_cheat.plugin.kts, game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/MapBuildCompleteHandler.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/model/interf/InterfaceSet.kt, game/src/main/kotlin/gg/rsmod/game/model/region/Chunk.kt, game/src/main/kotlin/gg/rsmod/game/sync/segment/PlayerLocationHashSegment.kt, game/src/main/kotlin/gg/rsmod/game/sync/task/PlayerPostSynchronizationTask.kt
=> Refactor & Fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/FormatTimePlayed.kt
- Refactor and comment FormatTimePlayed
- ye
=> Refactor and comment FormatTimePlayed

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/firemaking/FiremakingAction.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/ClickMapHandler.kt
Added checks so you cant light fires inside banks.
Fixed up Resting queue, so itll will finish the resting queue first, then continue
=> Firemaking fixes & resting queue

game/plugins/src/main/kotlin/gg/rsmod/plugins/util/anticheat/anti_cheat.plugin.kts
Added a check for inventory space when obtaining reward
=> Inventory free space check for anti cheat reward

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/quests/Quest.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/quests/QuestExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/RockType.kt
- Added support for Blurite ore (In preparation for The Knight's Sword quest)
- Added support for Quest Overview interface to show all Stat, Combat & Quest requirements and update string if requirements are met or not.
No, just some small edits.
=> Some fixes and some extra support for the Quest Overview Interface

game/plugins/build.gradle, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Objs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/core/FarmTicker.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/core/PlayerManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/CureType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Patch.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Sapling.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Seed.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/SeedType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/blocks/Harvest.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/blocks/SeedHarvest.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/npcs/Farmer.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/farmingInteractions.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/FarmingManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/PatchManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/PatchState.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/ChopHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/ClearHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/CureHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/GrowingHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/HarvestingHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/HealthCheckHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/SaplingGrowingHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/npcs/FarmerDialogue.kt
Adds bushes and fruit trees
Where needed, not much
=> Bushes and trees

game/plugins/src/main/kotlin/gg/rsmod/plugins/util/anticheat/anti_cheat.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
=> chore: add logout timer to anti-cheat

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/StringExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/dwarven_mines/mining_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/charter.plugin.kts, util/src/main/kotlin/gg/rsmod/util/Misc.kt
Fixed up some of my old dialogues i added in beginning, to use splitForDialogue
Also redone splitForDialogue
Added a string method to format numbers, you can use either thisInt.toString().formatNumber or you can use "hello this is number 123123".formatNumber() to format with commas. 
Fixed up some dialogues in sailing, mining guild etc.
Changed so default dialogue uses happy faces instead
=> Some dialogue fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/taverley/crystalkeys.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/DropTableType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/global/CrystalKeys.kt
Basic support for crystal keys
Not at the moment, it’s basic code though
=> wip: crystalkeys

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_6995.plugin.kts
=> added Ancient cavern spawns

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/equipment/equipment.plugin.kts, game/src/main/kotlin/gg/rsmod/game/fs/def/ItemDef.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt, game/src/main/kotlin/gg/rsmod/game/service/game/ItemMetadataService.kt
Equipment screen showing bonuses, to do is unequipping and equipping inside of interface, uploading so someone else can eventually add the remove and wear options
=> Equipment screen

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/draynor/ava.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12340.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/RangedCombatStrategy.kt
- Added Ava's npc spawn
- Added dialogue, npc options for Ava
- Added requirements (Animal Magnetism quest requirements)
- Added ability to purchase accumulators/attractors
- Added support for Accumulator/Attractor (attractor was missing)
- Yes
=> Ava and her shop & devices

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/scripts/combat_script_binding.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/scripts/impl/ImpCombatScript.kt
- Added a way for imps to randomly teleport, but issue is currently present with the Movement block for npcs. To be fixed by @alycii 
No
=> WIP Feature: Imp Teleportation/Combat

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawn_10038.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawn_10293.plugin.kts
added fishing spawns for barb outpost and fishing guild spawns
=> added barb outpost fishing spots and fishing guild spawns

data/packets.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/equipmentstats/equipment_stats_interface.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/equipment/equipment.plugin.kts, game/src/main/kotlin/gg/rsmod/game/message/handler/IfButton1Handler.kt
- Cleaned up the Equipment Stats interface code.
- Added support for "Stats" and "Examine" Options
- Added Examine option for Items (Inventory/Equipment)
- Not really, as It was mostly some cleaning up.
- Stats option needs to be added in the interface.
- Equipping & Un-equipping as well.
=> Some extra work on Equipment Stats interface

data/cfg/items.yml, data/packets.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/charter.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/daily/daily.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/christmas_cracker.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/loyalty/loyalty_points.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/shops/LoyaltyPointsCurrency.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/shops/PointCurrency.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/runetek5.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/util/anticheat/anti_cheat.plugin.kts, game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt, game/src/main/kotlin/gg/rsmod/game/message/MessageDecoderSet.kt, game/src/main/kotlin/gg/rsmod/game/message/decoder/OpPlayerTDecoder.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/OpPlayerTHandler.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/OpPlayerTMessage.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/model/timer/Timers.kt, game/src/main/kotlin/gg/rsmod/game/plugin/KotlinPlugin.kt, game/src/main/kotlin/gg/rsmod/game/plugin/PluginRepository.kt
- Added a player timer that ticks daily (24 hours)
- Added OpPlayerT packet (interface on player)
- Added Loyalty Points, which are given at a rate of 500 per day (every time daily timer ticks)
- Added Loyalty Point store, which contains rares and cosmetics
- Added Christmas Cracker plugin
- Added Halo item definitions
- Added Xuan plugin
- Changed some core logic with shops, including Points Currency
- Mostly
=> Loyalty Points/Rewards, support for Daily Timer

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/loyalty/loyalty_points.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/farmingInteractions.plugin.kts
=> chore: unlock farming

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/cooking_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/jewelleryenchanting/EnchantmentData.kt
=> Cooking guild pie shop

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/core/PlayerManager.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt
=> FarmingManager checks, fix RoW enchantment item

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatConfigs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/RangedCombatStrategy.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/equipmentstats/equipment_stats_interface.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/undeads/ghost_level_19.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/constants/Constants.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/core/PlayerManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/ClearHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/CompostBinHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/CompostHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/HarvestingHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/HealthCheckHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/RakeHandler.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt, game/src/main/kotlin/gg/rsmod/game/model/timer/TimerKey.kt, game/src/main/kotlin/gg/rsmod/game/model/timer/TimerMap.kt, game/src/main/kotlin/gg/rsmod/game/model/timer/Timers.kt, game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSerializer.kt
- Fixed Toktz-Xil thrown animation
- Fixed Ghost animations
- Changed some farming messages to be filtered
- Disabled some configurations on Equipment Bonus screen, was causing crashes
- Fixed an issue with farming timer not being removed properly
- Fixed an issue with harvesting items causing an NPE
- Fixed Earth Warrior blood rune drop
- Fixed Ring of Wealth enchantment product
=> An array of fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/asgarnia/thurgo.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/humanoids/mugger_level_6.plugin.kts
- Fix redberry pie dialogue for Thurgo
- Mugger definitions & drop tables.
No, just some fix and definitions
=> Redberry pie dialogue fix for Knights Quest & Mugger definitions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawn_16729.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawn_5190.plugin.kts
add spawns for glacor cave and frost dragons resource dungeon:
• frost dragons 
• glacor
=> spawns for glacor and frost dragons

.gitignore, data/cfg/items.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/amulet_of_glory.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/combat_bracelet.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/games_necklace.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/ring_of_dueling.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/ring_of_kinship.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/ring_of_wealth.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/skills_necklace.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/TeleportType.kt
Added all teleport types
Added Ring of wealth itemdefinitions
Added Skills necklace plugin
Added Amulet of glory plugin
Added Combat bracelet plugin
Added Ring of wealth plugin
Updated all old teleport types used, for ring of kinship, ring of dueling, games necklace
Yes
=> 2023-04-07

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/FlowerProtection.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/PatchState.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/GrowingHandler.kt
Ensures flowers protect allotments
No
=> feat: flowers properly protect allotments

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Seed.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/itemCreation/BasketItemCreation.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/itemCreation/SackItemCreation.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/farmingItemCreation.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/ClearHandler.kt
- Baskets can be filled with fruit
- Sacks can be filled with produce
- Scarecrows can be created, placed and removed
No
=> feat: fill baskets and sacks, and create scarecrows

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/watersource/WaterContainerData.kt
Allows all watering cans to be filled
No
=> feat: allow filling a watering can

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Objs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Patch.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Sapling.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Seed.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/SeedType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/npcs/Farmer.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/farmingInteractions.plugin.kts, game/src/main/kotlin/gg/rsmod/game/fs/NonTransmittedVarbitDefinitionProvider.kt, game/src/main/kotlin/gg/rsmod/game/fs/NonTransmittedVarpDefinitionProvider.kt
Adds the calquat tree
No, only data added
=> feat: add calquat tree

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/RangedCombatStrategy.kt
Added sounds to ranged weapons
=> feat: ranged weapon sounds

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/spinning/SpinningData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/data/SlayerMaster.kt
=> feat: add cave crawler to vannaka

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/taverley/taverley_stairs.plugin.kts
-removed array, replaced with list
-changed ladder handling function for objs in taverley
=> refactor: updated old taverley code

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Animations.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatAnimation.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatConfigs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/equipment/equipment.plugin.kts
Added CombatAnimation class
Added Animations class
Fixed attack & block animations is grabbed from CombatAnimation
Fix an issue where your weapontype wouldnt update upon equipping a shield when you wear a 2h.
Yes
=> Combat Animations

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/alkharid/zekes_scimitars.plugin.kts
Added Alkharid flyer dialogue when used on Zeke, also fix up some of the dialogues to use splitForDialogue
=> fix: added missing dialogues.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/MagicCombatStrategy.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/MagicSpells.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/SpellMetadata.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/SpellbookData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/alchemy/alchemy.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/jewelleryenchanting/EnchantmentData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/jewelleryenchanting/enchantment.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/superheat/superheat.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/telegrab/telegrab.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/teleports/teleport_spells.plugin.kts
added the sounds for all combat spells minus surge spells (cannot find sound ids anywhere)
added the sounds for alching
added sounds for enchanting
fixed the telegrab sound. 3008 is the sound for vulnerability
fixed some enchantment item ids (some were blank or placeholder items)
=> feat: normal spellbook sounds

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/charter.plugin.kts
Just a quick pr for renaming a method inside charter plugin
=> refactor: renamed a method inside charter plugin

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/PawnExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/combat.plugin.kts, game/src/main/kotlin/gg/rsmod/game/action/NpcDeathAction.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt
Combat fixes mostly
You can no longer attack another npc while you in combat and in a non-multi area.
Non needed, most of it was alrdy there
=> Combat Fixes 2023-04-16

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Food.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/pestle_and_mortar/PestleAndMortarData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/demons/black_demon_lvl_172.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/cooking/CookingData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/firemaking/FiremakingData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fishing/Fish.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fishing/FishingSpot.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fishing/FishingTool.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/herblore/mixing/PotionData.kt
foods here few for example
• added more meats 
• added more pastries
• added pies
• added stews
• added snails
• added stews
• added pizzas
• added more to vegetables 
• added dairies
• added fruits
• added gnome foods
• added dungeoneering foods (future content)
added more cooked foods here 
• cave eel
• slimy eel
• rainbow fish
• thin snail
• lean snail
• fat snail
added more potions
• added most of barbarian mixes potions
added more PestleAndMortar
• ground 
• dust
• paste
added more fish and fishing spots and tools
• leapings
• monkfish
• rainbow fish
• eels
• frogspawn
• barb fishing spot (outpost)
• monkfish (small net fishing)
=> feat: added more foods and cooked foods 

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/randoms/drill_demon.plugin.kts
- added an inventory check for the drill demon rewards
=> fix: drill demon reward inventory check

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/InterfaceDestination.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/dwarven_mines/living_rock_caverns.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/bank/Bank.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/bank/PawnExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/bank/bank.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/bank_locs/bank_booths.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/bank_locs/deposit_box.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/runetek5.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/starter/starter_kit.plugin.kts, game/src/main/kotlin/gg/rsmod/game/message/handler/MessagePublicHandler.kt, util/src/main/kotlin/gg/rsmod/util/Misc.kt
- Added deposit box interface, options
- Switched Pulley Lift to use the deposit box interface
- Added basic deposit boxes around the world
- Fixed a bug with closing tab area interfaces
- Cleaned up `openShop` code
- No
=> Deposit boxes

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/falador_castle.plugin.kts, game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt
- Implemented close-to RS emulation of executing code before reaching a pawn, which is in that you'll begin interacting with an pawn before your player completes the path to the pawn 
- Couple of ladder fixes
- Yes
=> Better pawn path actions

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/loyalty/loyalty_points.plugin.kts, game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt
=> fix: issue with pawn pathing

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/restoration/stat_restoration.plugin.kts
Fixes hitpoints regeneration
Yes
=> fix: hitpoints regeneration

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/lvlup/prayer_lvlup.plugin.kts, game/src/main/kotlin/gg/rsmod/game/plugin/PluginRepository.kt
Adds 10 prayer points for each prayer levelup
Yes
=> feat: gain prayer points on lvlup

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/edgeville/brass_key_door.plugin.kts
fixed an issue with compilation caused by an unremoved line of test code
=> fix: duplicate val declaration

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Animations.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatAnimation.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatConfigs.kt
Changed naming of start to default in Animations Class, aswell as removed end animation
No
=> refactor: changed naming from start to default in animations

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/morytania/temple_of_saradomin.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/critters/cave_bug_lvl_6.plugin.kts, game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt, game/src/main/kotlin/gg/rsmod/game/action/PlayerDeathAction.kt, game/src/main/kotlin/gg/rsmod/game/message/MessageEncoderSet.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
Addressed a few major bugs that broke the game.
Yes.
=> hotfix: patched invincibility bug and various game breaking bugs.

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/destroy_item.plugin.kts, game/src/main/kotlin/gg/rsmod/game/message/handler/IfButton1Handler.kt
Added the destroy item interface for all destroyable items.
https://github.com/2011Scape/game/assets/75695035/1468d58d-cecf-4def-9b54-32e88f432b3b
Yes
=> feat: added destroy item interface

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/father_aereck.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/father_urhney.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/ghost_coffin.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/restless_ghost.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/rock_with_skull.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/destroy_item.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/quests/TheRestlessGhost.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/prayer/burying/BoneData.kt
Added restless ghost quest <wip>
Yes.
=> feat<wip>: the restless ghost quest

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/scripts/combat_script_binding.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/scripts/impl/SkeletonWarlockCombatScript.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/undeads/skeleton_warlock_lvl_11.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/quests/impl/TheRestlessGhost.kt, game/src/main/kotlin/gg/rsmod/game/model/Graphic.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt
Added Skeleton Warlock Npc Definitions.
Yes.
=> feat: Added Skeleton Warlock NPC/Combat Definitions

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt
Included summoning into the combat level formula.
Yes.
=> fix: Corrected the combat level formula to include Summoning.

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/edgeville/oziach.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/agility/gnome_agility.plugin.kts, game/src/main/kotlin/gg/rsmod/game/fs/def/AnimDef.kt, game/src/main/kotlin/gg/rsmod/game/model/World.kt, util/src/main/kotlin/gg/rsmod/util/TextWrapping.kt
- Advanced gnome agility course
- Text wrapping for chatNpc and chatPlayer functions
- Yes.
https://github.com/2011Scape/game/assets/75695035/bb0bc314-2b3d-4f22-b505-6b735404b5da
=> feat: Added advanced gnome agility course and text wrapping for dialogues

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/toy_horsey.plugin.kts
Added logic for Toy Horseys.
I think it's pretty straight forward so no.
https://github.com/2011Scape/game/assets/4007910/a461e7db-7705-4d92-a415-f98919781893
=> feat: Implemented Toy Horsey Logic

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/specialattack/weapons/saradominsword/saradomin_sword.plugin.kts
- Added the special attack for the Saradomin Sword
Yes
First attempt at doing any combat changes. Let me know if there are any changes needed here
=> Add saradomin sword special attack

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/kandarin/fishing_guild.plugin.kts
-fixed level requirement for fishing guild gate.
=> bug: fixed level requirement for fishing guild gate.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/holidayitems/marionette.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/holidayitems/spinning_plate.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/holidayitems/yo_yo.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/holidayitems/zombie_head.plugin.kts
Added Marionette, Spinning plate and Yo Yo functionality. 
Where needed.
=> feat: more holiday items.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/holidayitems/yo_yo.plugin.kts
Fixed reference for yo-yo sound.
=> Fix: Fixed sound references for yo-yo.

game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSerializer.kt
Fixed a bug that would allow users to create accounts with the same username.
=> fix: fixed account duplication bug

game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSerializer.kt
=> bug: fix player saving.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/morytania/drezel.plugin.kts
- Fixed bug preventing players from finishing Priest in Peril when they give Drezel the exact amount of Rune Essence required to complete the quest.
- No.
=> bug: fixed issue preventing players from talking with Drezel.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/wilderness/wilderness_obelisk.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/TeleportType.kt
Added wilderness obelisks to help players navigate the wilderness.
Yes.
=> feat: added wilderness obelisks

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/PrayerIcon.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Sfx.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/formula/MagicCombatFormula.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/formula/MeleeCombatFormula.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/formula/RangedCombatFormula.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/PotionType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/PrayerGroup.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/Prayers.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/prayer.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/prayers.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/prayeraltar/prayer_altar.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/runetek5.plugin.kts, game/src/main/kotlin/gg/rsmod/game/message/handler/IfButton1Handler.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
- added prayer
- added prayer potions
Yes.
=> feat: prayer update

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/Ports.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/charter.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/scripts/combat_script_binding.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/random_event_gift.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/PrayerGroup.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/Prayers.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/prayer.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/prayers.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSaveData.kt, game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSerializer.kt
Prayer draining
Prayer drain timer fixed
Enabled Quick prayers (Not finished)
Fixed grouping of prayers (Restoration prayers mostly)
No
=> Prayer Updates

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/slayer/slayer_shop.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/Prayers.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
- wip adding slayer points reward shop
Yes.
=> feat<wip>: adding slayer points rewards shop

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/slayer/slayer_shop.plugin.kts
- added slayer points to shop interface
=> feat: added slayer points to shop.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/slayer/slayer_shop.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/Prayers.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/SlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/data/SlayerMaster.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/slayer_equipment_shop.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/slayer_masters_dialogue.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
- added slayer points rewards interface
- added weights to slayer assignments
Yes.
=> feat: slayer improvements

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/slayer/slayer_rewards.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/slayer_masters_dialogue.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt
- fixed bug causing blocked slayer tasks to not load correctly.
Yes.
=> bug: fixed bug loading players blocked slayer tasks

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/Prayers.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/prayers.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/runetek5.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
- added prayer stat adjustments panel to prayers interface.
- fixed bug causing infinite prayer when prayer points go below a value of zero.
Yes.
=> feat: prayer improvements

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/global/Rare.kt
- added santa hat to rare drop table for holiday event
=> feat: added santa hat to rare drop table

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/bucket_of_milk.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Food.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Foods.kt
- added item interactions for the following items: cavefish, buckets of milk
Yes, where necessary
=> content: buckets of milk and cavefish

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/dwarven_mines/mining_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Foods.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/mystery_box.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/Potion.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/PotionType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/Potions.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/superheat/superheat.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/undeads/ghost_level_19.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/arrows/ArrowAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/data/SlayerMaster.kt
- Santa hats can now be obtain from mystery boxes and the rares drop table.
- You can now access the dwarven mines from the ice mountain ladder.
- Ghosts in Varrock sewer now have the correct combat animations.
- added missing slayer task level requirement for rock slugs.
- fletching arrows now requires you to have a minimum of 15 arrow heads and 15 headless arrows.
- players can no longer superheat noted ores.
- Wine and beer are now drinkable.
- Yes.
=> feat: Christmas holiday event and various bug fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/edgeville/oziach.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/global/Rare.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/ring_of_forging.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/mystery_box.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/PotionType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/SpellbookData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/Mining.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/PickaxeType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/runecrafting/Altar.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/smithing/SmeltingAction.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
- Add all 667 revision items definitions to the game.
- Removed Christmas holiday event.
- Add ring of forging
- Add dwarven stout
- fix fire wave spell requiring the wrong runes
- fix body alter runecrafting
- fix oziach dialogue black screen client
- added mining role accumulator for dragon pickaxe
- Yes.
=> 667 Item Definitions Update and Bug Fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/yanille/magic_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/yanille/magic_guild/magic_store_owner.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/yanille/magic_guild/professor_imblewyn.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/yanille/magic_guild/robe_store_owner.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/yanille/magic_guild/wizard_frumscone.plugin.kts
- fixed magic guild doors and npcs dialogue.
=> chore: clean up magic guild content

game/src/main/kotlin/gg/rsmod/game/sync/task/PlayerSynchronizationTask.kt, game/src/main/kotlin/gg/rsmod/game/task/parallel/ParallelSynchronizationTask.kt
- fixed player desync and concurrency issues.
=> fix: potential desync / teleport issues

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/gadrin.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/yanille/magic_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/strategy/MagicCombatStrategy.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/combine/CombinationData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/cooking/CookingAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/cooking/CookingData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/cooking/raw_food_cooking.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/crafting/spinning/SpinningAction.kt, game/src/main/kotlin/gg/rsmod/game/service/GameService.kt, game/src/main/kotlin/gg/rsmod/game/task/parallel/ParallelSynchronizationTask.kt
- Add ability to make crossbows to fletching skill
- Add ability to make sinew on cooking range using cooking skill.
- Add ability to make crossbow strings using spinning wheel.
- Add chat dialogue for Gadrin the mining guild master, so players can now obtain mining skill capes.
=> feat: add ability to make crossbows

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/animals/black_unicorn_level_27.plugin.kts
Added the Black Unicorn plugin
Yes? Only because the code is the same as all the other NPC's.
=> Adding black unicorn

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts
- feat: add missing crown for owner privileges in players command
=> feat: add missing crown for owner privileges in players command

data/packets.yml, game/src/main/kotlin/gg/rsmod/game/message/decoder/OpNpc6Decoder.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/OpNpc6Handler.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/OpNpc6Message.kt
-  add movement type to npc option 6 packet
=> refactor: add movement type to npc option 6 packet

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/apeatroll/daga.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/apeatroll/hamab.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/apeatroll/ifaba.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/apeatroll/solihib.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/apeatroll/tutab.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/ardougne/richard's.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/burthorpe/anton.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/burthorpe/lidio.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/burthorpe/lilly.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/catherby/arhein.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/catherby/candle_maker_shop.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/sarah's.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/karamja/kofi.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/karamja/zambo.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/morytania/alice.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portphasmatys/ghost_shopkeeper.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/shilovillage/fernahei's.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/shilovillage/shilo_village_general_store.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/benny.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/other/gargoyle_lvl_111.plugin.kts
• added missing author
• added farming shops
• added todo
• modfile Vanessa shop to be right farming shop
=> missing author, farming shops, todo, vanessa shop,

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/entrana/entrana.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/lostcity_tree.plugin.kts
fixed the shamus spawn
fixed a dialogue queuing issue.
=> fix: some lost city fixes

data/cfg/gates/gates.json, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/asgarnia/crafting_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/asgarnia/master_crafter.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_11571.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/watersource/WaterContainerData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/level_up.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/RockType.kt
- added crafting guild entrance with level and brown apron requirements.
- added bank chest as a quality of life enhancement.
- add jug to items that can be filled with water.
- add gate to cow pen
Yes.
=> Feat: add crafting guild

README.md
=> Harley gilpin patch 1

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/BobBarter.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/FaridMorrisane.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/Hofuthand.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/MurkyMatt.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/ReloboBlinyo.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/ge/Sets.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/shops/ItemCurrency.kt
- Grand Exchange Armour Sets
- Grand Exchange Price Check NPC Dialogue
- Added skilling supplies shops to GE Npcs.
- Added Armour and Weapons shop to Hofuthand at GE.
Yes.
https://github.com/2011Scape/game/assets/75695035/db8c2bc7-fd40-4bd9-b716-7ed09037293e
=> Feat: Grand Exchange Armour Sets Interface and Shops

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/BobBarter.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/FaridMorrisane.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/Hofuthand.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/MurkyMatt.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/ReloboBlinyo.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/ge/Sets.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/shops/ItemCurrency.kt
=> Revert "Revert "Feat: Grand Exchange Armour Sets Interface and Shops""

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/BobBarter.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/FaridMorrisane.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/Hofuthand.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/MurkyMatt.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/grandexchange/ReloboBlinyo.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/ge/Sets.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/shops/ItemCurrency.kt
- Added Grand Exchange Amour Sets Exchange Interface
Yes.
=> Grand Exchange Armour Sets and GE Npc Dialogues

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/ghost_coffin.plugin.kts
Added an inventory space check for the end of the restless ghost.
=> fix: not getting restless ghost rewards

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/starter/starter_kit.plugin.kts, game/src/main/kotlin/gg/rsmod/game/Launcher.kt, game/src/main/kotlin/gg/rsmod/game/model/priv/Privilege.kt, game/src/main/kotlin/gg/rsmod/game/model/priv/PrivilegeSet.kt
- improvements to privileges and added promote/demote command for admins.
- added progress percentage while downloading the cache.
- Yes.
=> feat: added additional privilege identifiers for staff with inherited powers

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/taverley/crystal_chest.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/DropTableFactory.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/tables.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/constants/CompostState.kt, game/plugins/src/test/kotlin/gg/rsmod/plugins/content/drops/DropTableFactoryTest.kt, game/src/main/kotlin/gg/rsmod/game/action/ObjectPathAction.kt, game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt, game/src/main/kotlin/gg/rsmod/game/fs/def/ObjectDef.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/ClickMapHandler.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/ClickMinimapHandler.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt, game/src/main/kotlin/gg/rsmod/game/sync/segment/PlayerUpdateBlockSegment.kt
1. **Variable Renaming**: 
- Standardized variable names to follow camelCase convention for consistency (e.g., `TOOTH` → `tooth`, `CRYSTAL_CHEST` → `crystalChest`).
2. **Randomization Method Update**: 
- Replaced the usage of `SecureRandom` with `Random` for performance optimization where cryptographic security isn't required.
3. **Interaction Logic Enhancement**:
- Updated object interaction logic to ensure players face the correct direction when interacting with specific objects (e.g., Archery target adjustments).
- Improved face-object logic to reduce redundancy and handle multi-tile objects more effectively.
4. **Compost State Adjustments**:
- Corrected the `diseaseChanceFactor` for `Compost` and `SuperCompost` states to match accurate in-game behavior.
5. **Drop Table Logic …
=> feat<object interactions>: add pawn facing object interaction tile after clicking map/minimap.

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/src/main/kotlin/gg/rsmod/game/plugin/KotlinPlugin.kt
Re-added interface code which was deleted by accident during the KTLint PR
Yes
=> Re-add deleted code

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/signpost.plugin.kts
Added a signpost just south of the Shantay Pass entrance.
Source from http://youtu.be/5Ox3Yi8ZNL4
=> add Shantay pass signpost

data/cfg/npcs.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/explorer_jack.plugin.kts
Added explorer jack dialogue (bare min, no achievement stuff)
=> Added explorer jack dialogue

.gitignore, build.gradle, game.yml, game/src/main/kotlin/gg/rsmod/game/message/handler/MessagePrivateHandler.kt, game/src/main/kotlin/gg/rsmod/game/service/log/FileLoggerService.kt, game/src/main/kotlin/gg/rsmod/game/service/log/LoggerService.kt, game/src/main/resources/log4j2.xml
Implemented private message log saving to data/logs/private directory.
Yes.
=> Logger for Private Messages

build.gradle, game/src/main/kotlin/gg/rsmod/game/Launcher.kt, game/src/main/kotlin/gg/rsmod/game/Server.kt
- Added server commands "kick" and "teleport" that can be sent over Unix Domain Socket.
Yes.
=> Server commands and Unix Domain Socket Listener

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/lamps/lamp_interface.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/summoning/SummoningScrollData.kt
- Fixed an issue where players were unable to trade in their blood drain scrolls. (Also KTLint ran automatically on the file, actual fix is on line 330)
- Enabled summoning in the experience lamp interface
Yes
=> Various summoning fixes

data/packets.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/src/main/kotlin/gg/rsmod/game/message/MessageEncoderSet.kt, game/src/main/kotlin/gg/rsmod/game/message/encoder/CameraForceAngleEncoder.kt, game/src/main/kotlin/gg/rsmod/game/message/encoder/CameraLookAtEncoder.kt, game/src/main/kotlin/gg/rsmod/game/message/encoder/CameraMoveToEncoder.kt, game/src/main/kotlin/gg/rsmod/game/message/encoder/CameraResetEncoder.kt, game/src/main/kotlin/gg/rsmod/game/message/encoder/CameraShakeEncoder.kt, game/src/main/kotlin/gg/rsmod/game/message/encoder/CameraSmoothResetEncoder.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/CameraForceAngleMessage.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/CameraLookAtMessage.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/CameraMoveToMessage.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/CameraResetMessage.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/CameraShakeMessage.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/CameraSmoothResetMessage.kt
Added the following packets along with a `PlayerExt` function and an admin command for testing with each
- CameraForceAngleMessage
- CameraMoveToMessage
- CameraShakeMessage
- CameraLookAtMessage
- CameraResetMessage
- CameraSmoothResetMessage
Yes
=> Implement camera packets

data/packets.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/src/main/kotlin/gg/rsmod/game/message/MessageEncoderSet.kt, game/src/main/kotlin/gg/rsmod/game/message/encoder/MinimapToggleEncoder.kt, game/src/main/kotlin/gg/rsmod/game/message/impl/MinimapToggleMessage.kt
Added support for the MINIMAP_TOGGLE packet
Added ext function in player to send the packet
=> Add MinimapToggle packet support

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/ring_of_slaying.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/enchanted_gem.plugin.kts
- Added teleports to the Ring of Slaying
- Added the ability to craft Rings of Slaying at furnaces
- Moved some code from the Enchanted Gem plugin file to PlayerExt
Yes
=> Add Ring of Slaying functionality

data/cfg/objs.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/bookcase.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/church_ladders.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/crates.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/drawers.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/lumbridge_castle_ladders.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/lumbridge_fishing_supplies.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/tutorial_trapdoor.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12850.plugin.kts
- Changed a rat spawn that was on top of a sign post, moving it over 2 spaces
- Added interactions to bookcases
- Added interactions to the ladders inside lumbridge church
- Added interactions to the crate in the castle wall
- Added interactions to the various drawers around lumbridge
- Added interactions to the ladder behind lumbridge bank to go to the top
- Added some dialogue for Hank since he was lacking, removing any mentions of events that haven't occured yet.
- Added "functionality" to the tutorial trapdoor
- Removed the Priest Yauchomi (Prayer Tutor) as they were removed in an update in September 2009
- Added examine text to over 200 different game objects
=> Lumby cleanup

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/karamja/Luthas.kt
Fix a bug with Pirate's Treasure Quest
=> Fix a bug when getting a job with Luthas

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/draynor/fortunatos_fine_wine.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/bookcase.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/PickpocketTarget.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/Pickpocketing.kt
- Add Bookcase functionality (Wise Old Man's House)
- Fix a Chat option with fortunato that overlapped the screen
- Make Martin the Master Gardener pickpocketable
=> Quick-Add -> Post-Draynor Cleanup Additions 

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/father_aereck.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/bucket_of_milk.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/bucket_of_water.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/watersource/fill_water.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/quests/impl/TheRestlessGhost.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/RockType.kt
- Fixed Father Aereck dialogue to display correctly near the end of Restless Ghost
- Added a check during Restless Ghost quest completion to see if the player had room for the bones, if not add an attribute for it
- Added the dialogue to Father Aereck post-quest to give the player the bones as a reward if they did not have the inventory space to receive them when they initially completed the quest
- Added dialogue for Father Aereck to bless your clay rings into rings of devotion
- Added the (all 0) stats for the clay ring to make it wearable
- Fixed the message you receive when making soft clay
- Added some missing clay rocks that are located east of Draynor Manor and south of Barbarian village
- Added functionality for emptying buckets of water
- Added missing message when emptying …
=> Ring of devotion related additions (and more)

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Npcs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_10035.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_10036.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_10135.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_10136.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_10291.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_10292.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_11830.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_11832.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12086.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12599.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12630.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_13366.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_13456.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_13712.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_14235.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_4934.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_8008.plugin.kts
- Fixed Black Demon spawn in `spawns_4934.plugin.kts`
- Added Mourner to `spawns_8008.plugin.kts`
- Added Carla, Sarah, and Jethick to `spawns_10035.plugin.kts`
- Added Mourner to `spawns_10036.plugin.kts`
- Added Mourner to `spawns_10291.plugin.kts`
- Added Sick-looking Sheep (1, 2, 3, 4) to `spawns_10292.plugin.kts`
- Added Stubthumb to `spawns_11830.plugin.kts`
- Added Crate to `spawns_11832.plugin.kts`
- Added Brother Fintan to `spawns_12086.plugin.kts`
- Added Waldo to `spawns_12599.plugin.kts`
- Fixed incorrect spawns in `spawns_12630.plugin.kts`
- Added Squire Fyre to `spawns_13366.plugin.kts`
- Added Scabaras to `spawns_13456.plugin.kts`
- Added spawns to:
- `spawns_10135.plugin.kts`
- `spawns_10136.plugin.kts`
- `spawns_13712.plugin.kts`
- Added Experiment to …
=> feat: Spawn Updates & Fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/slayer_masters_dialogue.plugin.kts
=> fix non-wrapped slayer master dialogue that extends to more than 1 line

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/combat.plugin.kts
- Allows for special attack use during mutual aggression and in multi areas. (Previously couldnt use spec after combat was initiated)
=> Fix spec during combat

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/falador/waynes_chains.plugin.kts
- Added Wayne's chainbody shop in Falador
Yes
=> Add Waynes Chains

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/ardougne/captain_barnaby_ship.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/CharterType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/Ports.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/portsarim/charter.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_11058.plugin.kts
- Added Captain Barnaby/Customs officer dialogue for charter
- Added charter travel to/from Brimhaven/East Ardougne
- Added interactions to Captain Barnaby's Ship to be able to get on and off
yes
=> Ardougne <---> Brimhaven charter

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Combat.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/combat.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/aggro/npc_aggro.plugin.kts
- Multiway combat targeting now works as intended, and multiple targets will be able to aggro you at once and stay in combat with you.
- Single way combat should still work as before but with cleaner interactions.
- Cleaned up combat code very slightly and removed some redundant checks and also added some needed ones
=> Multi-way/single-way combat cleanup

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Anims.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_10554.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/scripts/combat_script_binding.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/scripts/impl/RockCrabsCombatScript.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/DropTableFactory.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/critters/rock_crab_lvl_13.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/critters/rocks.plugin.kts
- Fixed rock crab spawns in rellekka area
- Added rock crab changing mechanics
- Added rock crab defs/drops
- Also fixed a bug with item drops where if theres an item that dropped in a quantity more than 1 and was non-stackable would result in a single item containing multiple non-stackable items that would fill your inventory all at once
=> Rock crabs

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/king_roald.plugin.kts
- Dialogue typo and add anim to essence teleport
=> Quick fix: Dialogue typo and add anim to essence teleport

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12596.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/champions_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/guildmaster.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/scavvo.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/valaine.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/varrock/varrock_stairs.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/drawers.plugin.kts
- Added champions guild door, locked behind all quests being completed
- Added functionality to stairs/doors/chest/champion's challenge trapdoor
- Added dialogue to Guildmaster
- Added Scavvo dialogue and Scavvo's Rune Shop
- Added Valaine and Valaine's Shop of Champions
- Corrected the amount of chicken spawns in the garden area
- Added an arrive delay to drawers/staircases to match runescape functionality
=> Champions guild
