2011Scape/game

game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/model/skill/SkillSet.kt
Added a stat restore function to Player class which initialises on login and checks temporarily boosted stats against actual stats (determined by XP), decaying the difference by 1 level every minute checked.
-
-
-
=> Added stat restoration as per Issue #10

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/DropEntry.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/DropTableFactory.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/PickpocketTarget.kt
- Adds pickpocketing data
- Small adjustment to the drop table builder to allow specifying a range of quantities. Example: HAM members can drop 1 to 13 arrows.
- The drop table of the master farmer is not entirely correct, but should be close enough (for now)
- Black jacking targets have not been added yet
=> feat: add pickpocketing data

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/feathering/FeatherAction.kt
Feathering from an inventory that has no space for the product removes the product from the game. This ensures feathering can only be done when there's space for the product.
=> fix: check inventory before feathering

game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
Takes the xp multiplier into account when updating the xp counter
=> fix: Correctly update xp counter

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/Mining.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/smithing/SmeltingAction.kt
- Adds the correct player message upon failing to smelt an iron bar
- Fixes the player message upon mining an ore
- Ensures the mining animation gets updated in time. Previously, it would only get updated when a pickaxe would roll for success. This decouples pickaxe rolls from animation renewal.
There's probably a better way to "loop" an animation instead of continually renewing
Github makes a mess of the diff. Basically: the "success" logic was extracted to a separate function, and some tick logic was added to the main `mineRock` function
=> fix: renew mining animation in time

game/src/main/kotlin/gg/rsmod/game/action/NpcDeathAction.kt, game/src/main/kotlin/gg/rsmod/game/model/combat/DamageMap.kt
Reset the damage map when an npc gets reset
=> fix: Reset damage map when npc gets reset

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt
I noticed I could unequip my bow while ranging, and my character would continue attacking with ranged combat instead of using fists
=> fix: default to no weapon upon unequipping

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/apprentice_smith.plugin.kts
- Update Apprentice Smith dialogue to OldSchool RuneScape's current dialogue.
The items displayed in the message boxes need to be changed to the map icons representing a bank booth and furnace. To my knowledge, I thought these were sprites from cache dumps I have seen, so I was not sure how to display or find them. So, displayed are currently placeholder images, but they are similar to the dialogue message. I've written this sub-issue down in my own little project tasks, but I can always add it as an issue on here if need be.
=> update apprentice smith dialogue

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/take_hatchet.plugin.kts
Adds the ability to take the bronze hatchet from the logs in the lumbridge chicken coop. Respawns every minute.
=> Take-hatchet plugin.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/mining/Mining.kt
Walking to a rock starts the mining animation slightly later, which causes it to skip the second cycle
=> fix: fix mining animation when walking to rock

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Food.kt
Cakes heal 40 per bite, instead of 30. Also adds chocolate cakes because those can be gained from the bakery stall as well
=> fix: Add chocolate cake to foods and fix cake heal amount

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fishing/Fishing.kt
Continue fishing when inventory is full, but catching a fish would free up an inventory space
=> fix: continue fishing when inventory full with only one bait left

game/src/main/kotlin/gg/rsmod/game/service/xtea/XteaKeyService.kt
The `XteaKeyService` has been changed to check for a single JSON file regardless of it's name, and attempt to load that as the "single file" key mode. The `loadDirectory` method has been modified to ignore hidden files, such as the gitignore file. The motivation behind this change is that the link to the XTEA keys on the README has a different filename from what the server was previously expecting, and outputted no error message when it wasn't found, which is an unintuitive design.
- `XteaKeyService` now searches for a single JSON file and loads it as a single file, rather than looking for `xteas.json` specifically.
- `XteaKeyService` now ignores all files that have an empty filename when the extension is removed (that is, files beginning with a period).
=> Fix: Unintuitive behaviour when loading XTEA keys.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/Pickpocketing.kt
Adds the possibility for double, triple or quadruple pickpockets. Currently only works for double pickpockets on citizens, since all other multiples require an agility level higher than 1.
No sound implemented yet, I have no idea how to figure out the correct id
=> feat: multiple pickpockets

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/run/RunEnergy.kt
- changed the formula for run value restoration, courtesy of SkalFate on discord.
=> fix: adjusted run energy restore rates based on wiki values

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/MiscExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/run/RunEnergy.kt
An [update in 2009](https://runescape.wiki/w/Update:Run_energy_upgrade) changed the way energy depletion and restoration was calculated. Most notably, it ensured agility level played a role in both depletion and restoration.
There don't seem to be any relevant updates to those formula since then, so we can use the rs3-wiki for our data. However, the rs3 wiki is very inconsistent, claiming a restoration time of 1.15 minutes for 0-100% at 1 agility at [one place](https://runescape.wiki/w/Energy#Recovering_energy), and 0.45% per second (or 222 seconds) [at another](https://runescape.wiki/w/Rest).
The run energy page of [2011](https://runescape.wiki/w/Energy?oldid=9884152) agrees with the second source though, so I've taken that as the correct one. This gives, at level 1 agility:
- …
=> fix: run energy depletion and restoration was changed in 2009

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_greataxe_lvl_10.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_greataxe_lvl_17.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_spear_lvl_10.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_spear_lvl_17.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_twohand_sword_lvl_10.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/barbarian_twohand_sword_lvl_17.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/cow_level_2.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/farmer_level_7.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/giant_spider_level_2.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/guard_level_21.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/haakon_the_champion_lvl_29.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/lesser_demon_lvl_82.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/scorpion_level_14.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/unicorn_level_15.plugin.kts
- Adds charm drop tables to existing npc definitions
- Adds clue scrolls to existing npc definitions
- Adds one missing drop table
=> fix: add charms and clue scrolls to drop tables where needed

game/plugins/build.gradle, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/DropTable.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/drops/DropTableFactory.kt, game/plugins/src/test/kotlin/gg/rsmod/plugins/content/drops/DropTableFactoryTest.kt
Reduces the looping required for drop tables, especially larger tables. In the old situation, an array of `slots * 2` size was reserved, and a loop was performed of a total of `slots` times. In this proposed PR, the created list has a size of `amount of items and tables`, and a loop is performed of at most `(amount of items and tables) * 2`. This should improve performance for almost all tables.
The `SecureRandom` in the drop table factory is public for now to be able to easily test functionality. That can easily be made private again though.
=> Improve performance of drop tables

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/runecrafting/Rune.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/runecrafting/RunecraftAction.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/runecrafting/runecrafting.plugin.kts
In 2011, it was possible to obtain multiple runes per essence before the level for that multiplier was reached. According to the wiki of 2011, the chance for this scales from 0 to 60% between the previous and the next threshol level
=> feat: multi rune crafts can now trigger before the required level

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Combat.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/combat.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/aggro/npc_aggro.plugin.kts
- Added multi-way combat checks
- Re-installed NPC aggression plugin
- NPC aggression has had a couple changes, including checking if the radius was met and an attack was initiated, if not then interrupt all queues, interactions, and facing. Also added was a random check so that aggression wasn't "immediate" but gradual.
=> Npc aggression, multi-way combat

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/smithing/SmithingAction.kt
The max count when smithing items was calculated incorrectly - it should divide the bars in the inventory by the amount of bars per item, not muliply.
Also fixes the check in the canSmith function: if the amount is 0 or lower, we know there were not enough bars in the inventory.
=> fix: max count for smithing items was calculated incorrectly

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/QueueTaskExt.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/KeyTypedHandler.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/interf/InterfaceSet.kt
When producing an item box (fletching logs, spinning wool, smelting bars, etc..) you can now press keys on your keyboard to initialize the action.
For example, you want to fletch some regular logs, you use your knife on the logs and then press 1 to signal you want to fletch arrow shafts (as it's the first option in the item box)
Spacebar support has also been added, on which if you use key 2 for example, it'll remember that you pressed 2 and will act as though you pressed 2. This resets on a new item box being produced, and defaults to 1.
An example of a reset would be spacebar for fletching longbow (u) and then going to the spinning wheel, on opening the spinning wheel options, space bar will now act as key 1 and attempt to spin wool. This is also reset for fletching now, and spacebar …
=> Add support for keyboard keys 1-10, and spacebar for Item Box Actions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/aggro/npc_aggro.plugin.kts
- Removes the mainLoop@ from npc aggression, I believe this is the main cause for why it doesn't work on the official server. Will continue to debug if not.
=> Remove loop from npc-aggro

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/NpcParams.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/dsl/NpcCombatDsl.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Combat.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/black_bear_level_19.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/ghost_level_19.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/moss_giant_level_42.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/outlaw_level_35.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/combat/NpcCombatDef.kt
- Adds moss giant combat definition
- Adds ghost combat definition
- Adds black bear combat definition
- Adds outlaw combat definition
- Adds an npc combat setting "xpMultiplier". Any combat xp gained from attacking this npc is multiplied by that factor. Needed because outlaws only provide 2.5% as much xp as other monsters. Will be needed for the vampire in vampire slayer as well, for example
=> feat: more combat defs

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/prayer/burying/BoneData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/prayer/scattering/AshData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/prayer/scattering/ash_scattering.plugin.kts
Corrects a spelling mistake in BoneData.kt
Scattering animation is missing particle effect.
See: https://www.youtube.com/watch?v=Yv7KXYc4Pu4
Implements ash scattering as a prayer training method via the same implementation as bone burying.
Corrects a spelling mistake in BoneData.kt
No. I believe it is clear what is happening.
=> Adds ash scatting using the same implementation as burying bones.

README.md
Discord information will now display on the README, as well as licensing information.
=> Add discord widget to README

game/src/main/kotlin/gg/rsmod/game/model/attr/AttributeMap.kt, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSerializer.kt
The current code converts all double player attributes to ints on loading. This is fine, until we start using doubles or longs as attributes, such as the creation date. This PR fixes that, by making a distinction between ints, doubles and longs on saving and loading a player profile. Since type erasure is a thing in the JVM, there isn't really a clean way to do this.
This is a preparatory PR for the farming skill, where some long values need to be stored as well.
Yes
=> fix: data loss on long and double attributes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/CombatConfigs.kt
Weapons considered as long swords were previously using the lunge animation for regular attacks whilst it is supposed to use the slash animation. This addresses that issue.
No, just a simple id change
=> fix: Apply fix to give proper attack animation for weapons considered as Long Swords

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Objs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/core/PlayerManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/core/WorldFarmingManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Patch.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/farmingInteractions.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/GrowthManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/patchHandler/PatchVarbitUpdater.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/patchHandler/WeedsHandler.kt
Adds raking functionality to the Catherby herb patch. Weeds will regrow one stage each world farming tick.
Small bugfix to the player login logic for farming.
For now, attempting to rake as a normal player is not possible.
Yes
=> feat: Weeds farming

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/skillguides/skill_guides.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/constants/CompostState.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Seed.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/farmingInteractions.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/FarmingManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/PatchManager.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/InspectHandler.kt, game/src/main/kotlin/gg/rsmod/game/plugin/KotlinPlugin.kt, game/src/main/kotlin/gg/rsmod/game/plugin/PluginRepository.kt
- Introduces another plugin intializer: `on_any_item_on_obj`. This plugin triggers whever any item is used on the object. It is till possible to initialize using a specific item on that object: those plugins take precedence over the "general" plugin.
- Initializes all farming patches with the `on_any_item_on_obj` initializer
- Implements the `Inspect` option on farming patches
- In theory implements the `Guide` option on farming patches. This might require some deeper changes to really function though - it seems the server doesn't receive the request
Where needed
=> fix: less plugins

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/canoes/Canoe.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/canoes/CanoeUtils.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/canoes/canoes.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/canoes/canoes_interfaces.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/runetek5.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/plugin/KotlinPlugin.kt
- Canoes are now operational!
- Added a way to bind a single logic to multiple objects with different options: 
```kotlin
/**
* Invoke [logic] when the [options] option is clicked on multiple
* [gg.rsmod.game.model.entity.GameObject] at once.
*
* This checks multiple objects at the same time for possible options found in [options], then
* applies appropriate logic.
*/
fun on_obj_options(vararg objects: Int, options: Array<String>, lineOfSightDistance: Int = -1, logic: Plugin.() -> Unit) {
objects.forEach { o ->
val def = world.definitions.get(ObjectDef::class.java, o)
val slot = getSlot(def, *options)
check(slot != -1) { "None of the supplied options were found for object $o [options=${def.options.filterNotNull().filter { it.isNotBlank() }}]" }
r.bindObject(o, slot + 1, …
```
=> feat: Canoes are now operatable!

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/SpellbookData.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/alchemy/alchemy.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/superheat/superheat.plugin.kts
feat: Add Superheat Item spell with Smithing experience
- Implement Superheat Item spell
- Add logic to handle different ores and their corresponding bars
- Account for Coal requirements when superheating certain ores
- Provide Smithing experience based on the type of bar produced
Also fixed tick delay for alchemy.
=> Magic: Add Superheat Item spell 

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/ChopHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/ClearHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/CompostHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/CureHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/FarmingTimerDelayer.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/HarvestingHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/HealthCheckHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/PlantingHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/RakeHandler.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/WaterHandler.kt
Slightly delay the player farming timer if it would reach zero during a player farming action
No, only small adjustments
=> fix: ensure farming ticks don't occur during player queue

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/data/Seed.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/PatchState.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/logic/handler/CureHandler.kt, game/src/main/kotlin/gg/rsmod/game/plugin/PluginRepository.kt
- Don't use lives varbit for producing crops. Lives are contained in the main varbit for these crops and using the lives varbit as well can lead to bugs
- Don't use plant cures to fix a tree - this needs secateurs
- Fix to find the correct plugin when any item is used on an object, where that item can also be used on other objects. This fixes not being able to compost sweetcorn, for example
No
=> fix: some farming fixes

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/beefy_bill.plugin.kts
- the code for calculating the amount of items bill takes was sometimes showing 0
- no, simple math change
=> fix: calculations for beefybill dialogue

data/packets.yml, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/InterfaceDestination.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/TileExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/wilderness/wilderness.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Combat.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/jewellery/amulet_of_glory.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/watersource/fill_water.plugin.kts, game/src/main/kotlin/gg/rsmod/game/message/MessageDecoderSet.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/OpPlayer2Handler.kt, game/src/main/kotlin/gg/rsmod/game/model/interf/InterfaceSet.kt
- Added OpPlayer2 packet ("Attack")
- Added Wilderness plugin, which checks current wilderness level and updates Attack option/overlay
- Changed the message when trying to attack someone who is higher/lower level than your current wilderness level
- Fixed an issue with `Empty` option not available on Watering Can(8)
- Used the formula taken directly from CS2 Script (54) for the Wilderness level check
- Added region checks for wilderness
- Fixed amulet of glory degradation message
- No
=> Wilderness

data/cfg/gates/gates.json, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Objs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12107.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12619.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/wilderness/dark_mage.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Combat.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/random_box.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/magic/PawnExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/gates/gates.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/abyss.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/randoms/drill_demon.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/randoms/random_event_handler.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Npc.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
This pull request adds an anti-cheat mechanism for the Drill Demon random event in the game. The mechanism works by tracking successful completions of the event and penalizing players who log out or fail to complete the event before logout. The penalization is implemented by increasing a flag called BOTTING_SCORE attached to the player's account.
Successful completions of the event will decrease the BOTTING_SCORE towards zero. However, negative integers are not possible, so repeat offenders will still have a score greater than zero, making it easier to identify and take action against them.
The Drill Demon event is randomly triggered between 25 and 90 minutes, during which the demon follows the player around the map until they talk to him.
- [fix: added death altar to abyss runecrafting …
=> feat: added drill demon random event

game/plugins/src/main/kotlin/gg/rsmod/plugins/api/ext/PlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/wilderness/mage_of_zamorak.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/prayeraltar/prayer_altar.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/runetek5.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt, game/src/main/kotlin/gg/rsmod/game/model/timer/Timers.kt, game/src/main/kotlin/gg/rsmod/game/service/serializer/json/JsonPlayerSerializer.kt
Uses the proper varbit for representing prayer points. Fixes altars not working. Properly reset prayer points when entering the abyss.
Uses a 1-tick timer on login to ensure the client displays the correct prayer point value. For some reason, this doesn't work on the login-tick but has to be performed after login.
Yes
=> fix: use proper varbit for prayer points

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawn_10394.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_12693.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/lightsource/LightSource.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/other/ice_giant_level_53.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/definitions/other/ice_warrior_level_57.plugin.kts
spawns for (waterfall dungeon)
• shadow spiders
• skeleton mages
• fire giants
---------------------------------------------------------------------------------
fix spawn for lumbridge sawm caves
its was stuck in rock
• cave slime
----------------------------------------------------------------------------------
lightsources 
• unlit torch
• white candle lantern
• black candle lantern
• oil lamp
• oil lantern
• bullseye lantern
=> feat; spawn for 10394 (waterfall dungeon)

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/stalls/StallTarget.kt
update the game message on successful thieve of baker's and crafting stall
=> fix: update baker and crafting stall thieving message

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/randoms/random_event_handler.plugin.kts
You could skip the drill demon random event by simply running away in time. This change makes sure there's no way to avoid a forced teleport to his area.
No, simple change to a lockingQueue
=> fix: drill demon force teleports

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/edgeville/brass_key_door.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/furnaces/furnaces.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fletching/stringing/BowStringAction.kt
- the door for hill giants exists now when opening, no longer vanishes
- furnace interface no longer pops up with 2 interfaces when you have a regular ore and a gold / silver ore (for jewelery)
- requires a mold and a silver or gold bar to pop up with jewellery smithing interface. this prevents players from seeing both interfaces on screen unless the player has both a smithable ore and a combination of silver or gold and a mould.
- made stringing messages filterable
=> fix: multiple bugfixes (read commits)

data/cfg/objs.yml
Most object examine messages were incorrect. For example, the examine message for the ID 2647 was "A picture of a fruit bowl." However, the ID 2647 matches to the door of the Crafting Guild. Now, the message for the ID 2647 is "The door to the Crafting Guild." From what I understand, the old examine messages were from OSRS and a lot of the object IDs do not match those from the revision 667 of RS. The new examine messages are from a revision 377 cache, which is the last RS revision that I could find that included them locally in the cache. After that, they were server-sided only and nobody seems to have a dump of them, at least publicly. For this reason, I used a revision 377 cache which contains the examine messages for the IDs 0 - 14973. This explains why I also removed all examine …
=> feat: fix/remove incorrect object examine messages and add new ones

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/morytania/temple_of_saradomin.plugin.kts
Fixes a bug in the Priest in Peril quest. When swapping the keys at the monuments, first remove the golden key, then add the iron key to the inventory
=> fix: swapping the golden key with a full inventory voids the iron key

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/skillguides/skill_guides.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/skill/SkillSet.kt
Attempting to set a target level for dungeoneering over level 99 would result in a message saying you cannot do so. This PR fixes that and allows a target level of up to 120.
- Add `SkillSet.MAX_LVL_DUNGEONEERING = 120`
- Update skill guides plugin `canSetTarget()` logic to account for dungeoneering's max level
Yes, where needed
=> fix: allow dungeoneering to have a target level above 99

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_14415.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_14416.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_14671.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_14672.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/slayer/slayer_rewards.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/inter/slayer/slayer_shop.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/prayer/Prayers.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/randoms/random_event_handler.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/fishing/fishing.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/SlayerExt.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/data/SlayerMaster.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/slayer_equipment_shop.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/slayer_masters_dialogue.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Player.kt
- added slayer points reward for completing slayer assignments. (bonus for completing consecutive tasks.)
- added slayer rewards shop to buy slayer supplies, learn new abilities, and manage your task assignments.
- added weights to slayer task assignment frequency.
- drill demon will no longer teleport you to Lumbridge as a punishment for failing the event.
- fixed bug with rocktail fishing spots
Yes.
=> feat: slayer rewards shop and drill demon random event adjustment

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Food.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Foods.kt
We eatin good tonight.
Source is the RS Wiki from October 2011: https://runescape.wiki/w/Kebab?oldid=4868155
This is basic, but I believe it's also fully authentic as well. This PR is actually pretty important too because kebab is an early-game food and many players' early-game strategy involves making use of kebabs, which is now possible with this PR.
Added basic kebab eating.
Surprisingly, yes.
=> feat: Added basic kebab eating

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/src/main/kotlin/gg/rsmod/game/model/attr/Attributes.kt
- added "locate" command (searches region id and matches that to a list in a function)
- fixed "players" command to not have an interface pop up and to show a list of the first 10 players the game finds online. also fixed grammar when calling this command
=> feat: fixed players command and added locate command

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/alkharid/alkharid_gate.plugin.kts
Fixed Al Kharid border guards charging GP when they aren't supposed to (after the player has completed Prince Ali Rescue quest).
Where necessary and as much as the rest of the file, yes.
=> Fixed Al Kharid border guards always charging GP

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/slayer/data/SlayerMaster.kt
Fixed banshees being assigned as a slayer task before 15 slayer, they require 15 slayer because of earmuffs. 
No, it's not necessary because the surrounding code is not either.
=> Fixed banshees not requiring 15 slayer

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/thieving/pickpocketing/Pickpocketing.kt
- Reduced the agility level overshoot needed for triple loot by 10
Yes
Fixes #466
=> fix: reduce agility overshoot needed for triple loot

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_9525.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/spawns/spawns_9526.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Food.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/swamp_toad.plugin.kts
- Added swamp toad spawns to the swamp in north-western gnome stronghold
- Added swamp toad spawns to the lake in south-western gnome stronghold
- Added the ability to remove swamp toad legs from the toads
- Added the ability to eat toad legs
Yes
https://runescape.wiki/w/Toad%27s_legs?oldid=4987128
https://runescape.wiki/w/Swamp_toad?oldid=3893849 
South west stronghold spawns are not mentioned here but are present in OSRS and mentioned in a later 2014 update leading me to believe they would be there in 2011. 2014 update referenced a spawn in the middle of the south western lake which has been retained
https://oldschool.runescape.wiki/w/Swamp_toad_(item) 
Used for spawn locations
Respawn cycle 90 is based off of previously existing spawns for region 11573 (Taverly)
=> feat: add swamp toad spawns and functionality

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/combine/CombinationAction.kt
- Fixed the CombinationAction canCombine function to check the CombinationData's skill and not just crafting
Before
After
Yes
=> fix: combination action checks proper skill and not just crafting

game/build.gradle, game/plugins/build.gradle, game/plugins/src/main/kotlin/gg/rsmod/plugins/api/cfg/Objs.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/asgarnia/crafting_guild.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/cmd/commands.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/Combat.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/canoes/canoes.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/npcwalk/npc_random_walk.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/npcs/duck/duck.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/bank_locs/deposit_box.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_cabbage.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_flax.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_onion.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_potato.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/objs/pick/pick_wheat.plugin.kts, game/src/main/kotlin/gg/rsmod/game/action/GroundItemPathAction.kt, game/src/main/kotlin/gg/rsmod/game/action/ObjectPathAction.kt, game/src/main/kotlin/gg/rsmod/game/action/PawnPathAction.kt, game/src/main/kotlin/gg/rsmod/game/fs/def/ObjectDef.kt, game/src/main/kotlin/gg/rsmod/game/message/handler/OpLoc1Handler.kt, game/src/main/kotlin/gg/rsmod/game/model/Direction.kt, game/src/main/kotlin/gg/rsmod/game/model/MovementQueue.kt, game/src/main/kotlin/gg/rsmod/game/model/World.kt, game/src/main/kotlin/gg/rsmod/game/model/collision/CollisionFlagMapExt.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Npc.kt, game/src/main/kotlin/gg/rsmod/game/model/entity/Pawn.kt, game/src/main/kotlin/gg/rsmod/game/service/game/ObjectMetadataService.kt, gradle.properties
- Implemented objects and ground item interactions with the new RSMod Pathfinding (version 5.0).
- Improved naming in the ObjectDef class.
- Fixed bug with random event timer throwing ConcurrentModificationException error.
- Added pawn canSwim flag for ducks so they can "swim" on water tiles.
- Added col_map command to print out collision flags around a player. Useful for debugging pathfinding.
- Add object interaction exception for pathing to the Target objects in the Ranging Guild.
https://github.com/2011Scape/game/assets/75695035/8aafbf99-f67c-42ff-a4c7-953ac7d6f2bf
https://github.com/2011Scape/game/assets/75695035/168e108a-4780-43f8-988f-71992fa72245
Yes.
=> Fix Pathfinding for Interacting with objects

game/src/main/kotlin/gg/rsmod/game/action/ObjectPathAction.kt
- Adjusted the isPathBlocked flag to target the correct tile for furnace objects to prevent incorrectly blocking the furnace when players interact with them.
=> fix: adjusted isPathBlocked flag to support interactions with furnaces.

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/food/Foods.kt
Kebabs were only healing 10% of what they should be. At 190 constitution, they would only heal 1 instead of 10 - this is of course very obviously incorrect. This fixes that issue since the Player's max constitution level is already 10% of their total constitution. I have tested and double checked that it now heals the proper amount.
I fixed a bug in some code I wrote. Kebabs now heal the proper amount.
The existing code and the bug fix are both fully commented yes.
=> fix: Fixed kebab heal amount

game/src/main/kotlin/gg/rsmod/game/message/encoder/RebuildNormalEncoder.kt
REBUILD_NORMAL should always be sending a specific amount of keys based on its build area, and the forceSend logic / skipping specific areas circumvents that logic and results in a client crash.
This fixes that!
No :)
=> fix: Sending keys for all regions

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/Potion.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/items/potion/PotionType.kt, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/mechanics/run/RunEnergy.kt
Added energy potion functionality
=> Add energy pots

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/level_up.plugin.kts
Fixing bug where you get a message that says you reached max combat at level 126, but with Summoning it was raised to 138.
=> Change combat level message for max combat from lvl 126 to 138

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/father_urhney.plugin.kts, game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/rock_with_skull.plugin.kts
- Fix a bug where player could complete the quest but not receive the rewards or quest points, by interacting with the rock multiple times after destroying the muddy skull
- Made it so the warlock does their spawn animation properly and then attacks the player
- Added a missing interaction with empty rock
- The player is now the "owner" of the spawned warlock, which will disappear upon logout instead of sticking around
- The player can no longer spawn more warlocks if there is already one spawned for the player
=> Restless ghost cleanup

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/skills/farming/constants/CompostState.kt
Wiki states disease rate for supercompost is reduced to 14% chance of disease, while regular compost is half as effective, only reduced to a 28% chance of disease)
Rates were previously erroneously swapped, where regular compost was giving much better disease rates than super compost 
- Fixed the disease ratios for compost to actually match wiki, making sure supercompost is actually better than normal compost (in this case lower ratio means less chance for disease)
=> Fix Compost disease rates to actually match wiki rate

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/combat/formula/MagicCombatFormula.kt
- Magic combat for npc uses the default formula for damage if there is no spell being cast. 
This allows npcs with special combat mechanics (like revenants/aberrant spectres) to do damage that isn't a 1
=> Fix NPC magic combat

game/src/main/kotlin/gg/rsmod/game/model/World.kt
- Added the option to set the exit tile for instances created using `createTemporaryInstance`. Currently it just uses `gameContext.home` (Lumbridge). This will remain as the default.
=> Add setting exit tile to createTemporaryInstance

game/plugins/src/main/kotlin/gg/rsmod/plugins/content/areas/lumbridge/warrior.plugin.kts
- Changed a > to a >= check when checking woodcutting level requirements for starting the quest. Previously you were unable to start the quest with 36 woodcutting because of the erroneous check
=> Quick Fix: Fix Lost City starting requirements check in dialogue
